apiVersion : apps/v1
kind: Service
metadata:
  name: go-app
  namespace: go-survey
  labels:
    app: go-app
spec:
  selector:
    app: myapp
  type: NodePort
  ports:
    - name: go-app
      port: 8080
      targetPort: 8080  

---
apiVersion : apps/v1
kind: Service
metadata:
  name: mongo-app-service
  namespace: go-survey
  labels:
    app: mongo-app
spec:
  selector:
    app: myapp
  type: NodePort
  ports:
    - name: mongo-app
      port: 27017
      targetPort: 27017  
  


















